# Generated by Django 5.2.7 on 2025-12-05 05:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_delete_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Laporan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kode", models.CharField(blank=True, max_length=64, unique=True)),
                ("jenis", models.CharField(max_length=120)),
                ("lokasi", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("link_pelaporan", models.URLField(blank=True)),
                ("is_anonim", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("diterima", "Laporan Diterima"),
                            ("verifikasi_awal", "Verifikasi Awal"),
                            ("wawancara_pelapor", "Wawancara Pelapor"),
                            ("wawancara_terlapor", "Wawancara Terlapor"),
                            ("pengumpulan_bukti", "Pengumpulan Bukti"),
                            ("rapat_pemutusan", "Rapat Pemutusan"),
                            ("rekomendasi", "Rekomendasi"),
                            ("pelaksanaan", "Pelaksanaan Tindak Lanjut"),
                            ("ditutup", "Ditutup"),
                            ("ditolak", "Ditolak"),
                        ],
                        default="diterima",
                        max_length=32,
                    ),
                ),
                ("rekomendasi", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pelapor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="evidence/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidences",
                        to="users.laporan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(max_length=64)),
                ("catatan", models.TextField(blank=True)),
                ("tanggal", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="users.laporan",
                    ),
                ),
                (
                    "oleh",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
