# Generated by Django 5.2.7 on 2025-12-05 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_laporan_evidence_progress"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("waktu", models.TimeField()),
                ("konselor", models.CharField(max_length=255)),
                ("nama", models.CharField(max_length=255)),
                ("topik", models.TextField(blank=True)),
                ("jenis", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("terjadwal", "Terjadwal"),
                            ("selesai", "Selesai"),
                            ("dibatalkan", "Dibatalkan"),
                        ],
                        default="terjadwal",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-tanggal", "-waktu"],
            },
        ),
    ]
