# Generated by Django 5.2.7 on 2025-12-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_counselor_booking_konselor_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="alasan_pembatalan",
            field=models.TextField(blank=True, null=True),
        ),
    ]
