# Generated by Django 5.2.7 on 2025-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_booking_alasan_pembatalan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Konten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("kesadaran", "Kesadaran"),
                            ("pencegahan", "Pencegahan"),
                            ("dukungan", "Dukungan"),
                            ("informasi", "Informasi"),
                        ],
                        default="informasi",
                        max_length=20,
                    ),
                ),
                (
                    "deskripsi",
                    models.TextField(help_text="Deskripsi singkat untuk card"),
                ),
                ("konten", models.TextField(help_text="Isi artikel lengkap")),
                (
                    "gambar",
                    models.ImageField(blank=True, null=True, upload_to="konten/"),
                ),
                (
                    "penulis",
                    models.CharField(default="Tim Ruang Dengar", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Konten",
                "verbose_name_plural": "Konten",
                "ordering": ["-created_at"],
            },
        ),
    ]
