# Generated by Django 5.2.7 on 2025-12-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_konten"),
    ]

    operations = [
        migrations.AddField(
            model_name="konten",
            name="scheduled_date",
            field=models.DateTimeField(
                blank=True, help_text="Tanggal publikasi terjadwal", null=True
            ),
        ),
    ]
