# Generated by Django 5.2.7 on 2025-12-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0013_konten_scheduled_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="konten",
            name="media_url",
            field=models.URLField(
                blank=True,
                help_text="Link ke PDF, YouTube, atau media eksternal lainnya",
                max_length=500,
                null=True,
            ),
        ),
    ]
