# Generated by Django 5.2.7 on 2025-12-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_konten_media_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="laporan",
            name="ai_analyzed",
            field=models.BooleanField(
                default=False, help_text="Sudah dianalisis AI atau belum"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="ai_kategori",
            field=models.CharField(
                blank=True,
                help_text="Kategori otomatis dari AI",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="ai_needs_blur",
            field=models.BooleanField(
                default=False, help_text="Apakah konten perlu di-blur"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="ai_toxicity_score",
            field=models.FloatField(
                blank=True, help_text="Skor toksisitas (0-1)", null=True
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="ai_urgency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("darurat", "Darurat"),
                    ("tinggi", "Tinggi"),
                    ("sedang", "Sedang"),
                    ("rendah", "Rendah"),
                ],
                help_text="Tingkat urgensi dari AI",
                max_length=20,
                null=True,
            ),
        ),
    ]
