# Generated by Django 5.2.7 on 2025-12-05 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_laporan_ai_analyzed_laporan_ai_kategori_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                help_text="Foto profil pengguna",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("laporan_baru", "Laporan Baru"),
                            ("booking_baru", "Booking Baru"),
                            ("laporan_darurat", "Laporan Darurat"),
                            ("status_laporan", "Update Status Laporan"),
                            ("jadwal_berubah", "Perubahan Jadwal"),
                            ("jadwal_dibatalkan", "Jadwal Dibatalkan"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.booking",
                    ),
                ),
                (
                    "laporan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="users.laporan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notifikasi",
                "verbose_name_plural": "Notifikasi",
                "ordering": ["-created_at"],
            },
        ),
    ]
