# Generated by Django 5.2.7 on 2025-12-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_customuser_profile_picture_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin_approval_date",
            field=models.DateTimeField(
                blank=True, help_text="Tanggal admin disetujui", null=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_approved",
            field=models.BooleanField(
                default=True,
                help_text="Untuk admin: apakah sudah disetujui oleh super admin",
            ),
        ),
    ]
