# Generated by Django 5.2.7 on 2025-12-05 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_customuser_admin_approval_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="konten",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Tags dipisah koma, contoh: bullying,kekerasan fisik,pelecehan",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="konten",
            name="view_count",
            field=models.IntegerField(
                default=0, help_text="Jumlah kali artikel dibuka"
            ),
        ),
    ]
