# Generated by Django 5.2.7 on 2025-12-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_konten_tags_konten_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="alamat",
            field=models.TextField(
                blank=True,
                help_text="Alamat tempat tinggal",
                null=True,
                verbose_name="Alamat",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nomor_telepon",
            field=models.CharField(
                blank=True,
                help_text="Nomor telepon pribadi",
                max_length=20,
                null=True,
                verbose_name="Nomor Telepon",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="nomor_telepon_kerabat",
            field=models.CharField(
                blank=True,
                help_text="Nomor yang dapat dihubungi dalam keadaan darurat",
                max_length=20,
                null=True,
                verbose_name="Nomor Telepon Kerabat/Orangtua",
            ),
        ),
    ]
