# Generated by Django 5.2.7 on 2025-12-06 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_customuser_alamat_customuser_nomor_telepon_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="status",
            field=models.CharField(
                choices=[
                    ("diterima", "🔵 Laporan Diterima"),
                    ("verifikasi_awal", "⏳ Verifikasi Awal"),
                    ("wawancara_pelapor", "🗣️ Wawancara Pelapor"),
                    ("pengumpulan_bukti", "📁 Pengumpulan Bukti Tambahan"),
                    ("wawancara_terlapor", "⏳ Wawancara Terlapor"),
                    ("analisis_kronologi", "🔍 Pemeriksaan Kronologi & Analisis Bukti"),
                    ("rapat_pemutusan", "🧩 Rapat Pemutusan Kasus"),
                    ("rekomendasi", "📌 Rekomendasi Tindak Lanjut"),
                    ("pelaksanaan", "🚀 Pelaksanaan Tindak Lanjut"),
                    ("ditutup", "✔ Kasus Ditutup"),
                    ("ditolak", "❌ Ditolak"),
                ],
                default="diterima",
                max_length=32,
            ),
        ),
    ]
