# Generated by Django 5.2.7 on 2025-12-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0020_update_status_choices_ppkpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="catatan_admin",
            field=models.TextField(
                blank=True, help_text="Catatan dari admin untuk mahasiswa", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="lokasi_konseling",
            field=models.CharField(
                default="REK-407", help_text="Ruangan konseling", max_length=255
            ),
        ),
    ]
