# Generated by Django 5.2.7 on 2025-12-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_add_booking_location_and_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="fakultas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fakultas Teknik Elektro", "Fakultas Teknik Elektro"),
                    ("Fakultas Rekayasa Industri", "Fakultas Rekayasa Industri"),
                    ("Fakultas Informatika", "Fakultas Informatika"),
                    ("Fakultas Ekonomi dan Bisnis", "Fakultas Ekonomi dan Bisnis"),
                    (
                        "Fakultas Komunikasi dan Ilmu Sosial",
                        "Fakultas Komunikasi dan Ilmu Sosial",
                    ),
                    ("Fakultas Industri Kreatif", "Fakultas Industri Kreatif"),
                    ("Fakultas Ilmu Terapan", "Fakultas Ilmu Terapan"),
                    ("Telkom University Purwokerto", "Telkom University Purwokerto"),
                    ("Telkom University Jakarta", "Telkom University Jakarta"),
                    ("Telkom University Surabaya", "Telkom University Surabaya"),
                ],
                max_length=100,
                null=True,
                verbose_name="Fakultas",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_profile_complete",
            field=models.BooleanField(
                default=False,
                help_text="Apakah profil sudah lengkap (untuk Google OAuth)",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="no_whatsapp",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Nomor WhatsApp"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="status_pengguna",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mahasiswa", "Mahasiswa"),
                    ("Dosen", "Dosen"),
                    ("Tenaga Penunjang Akademik", "Tenaga Penunjang Akademik"),
                ],
                max_length=50,
                null=True,
                verbose_name="Status",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="usia",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Usia"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="apakah_korban_langsung",
            field=models.BooleanField(
                default=True, help_text="Apakah pelapor adalah korban langsung"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="asal_instansi_terlapor",
            field=models.CharField(
                default="Telkom University",
                max_length=255,
                verbose_name="Asal Instansi Terlapor",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="fakultas_korban",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Fakultas Korban"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="fakultas_terlapor",
            field=models.CharField(
                default="", max_length=100, verbose_name="Fakultas Terlapor"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="hubungan_pelapor_korban",
            field=models.CharField(
                blank=True,
                help_text="Jika bukan korban langsung, hubungan dengan korban",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="hubungan_terlapor_korban",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="Hubungan Terlapor dengan Korban",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="jenis_kelamin_korban",
            field=models.CharField(
                blank=True,
                choices=[("Laki-laki", "Laki-laki"), ("Perempuan", "Perempuan")],
                max_length=20,
                null=True,
                verbose_name="Jenis Kelamin Korban",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="jumlah_terlapor",
            field=models.CharField(
                choices=[
                    ("1 Orang", "1 Orang"),
                    ("Lebih dari 2 Orang", "Lebih dari 2 Orang"),
                ],
                default="1 Orang",
                max_length=20,
                verbose_name="Jumlah Terlapor",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="kronologi_singkat",
            field=models.TextField(
                default="",
                help_text="Ringkasan singkat kejadian",
                verbose_name="Kronologi Singkat",
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="nama_korban",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nama Korban"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="nama_terlapor",
            field=models.CharField(
                default="Tidak Diketahui", max_length=255, verbose_name="Nama Terlapor"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="nim_nip_korban",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="NIM/NIP/NIK Korban"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="nim_nip_terlapor",
            field=models.CharField(
                default="", max_length=50, verbose_name="NIM/NIP/NIK Terlapor"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="no_wa_terlapor",
            field=models.CharField(
                default="", max_length=20, verbose_name="No WhatsApp Terlapor"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="prodi_korban",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Prodi Korban"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="prodi_terlapor",
            field=models.CharField(
                default="", max_length=100, verbose_name="Prodi Terlapor"
            ),
        ),
        migrations.AddField(
            model_name="laporan",
            name="status_korban",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Status Korban"
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="deskripsi",
            field=models.TextField(
                help_text="Ceritakan kronologi lengkap kejadian",
                verbose_name="Deskripsi Lengkap",
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="is_anonim",
            field=models.BooleanField(
                default=False, help_text="Rahasiakan identitas dari terlapor"
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="jenis",
            field=models.CharField(
                choices=[
                    ("Kekerasan Fisik", "Kekerasan Fisik"),
                    ("Kekerasan Psikis", "Kekerasan Psikis"),
                    ("Kekerasan Fisik dan Psikis", "Kekerasan Fisik dan Psikis"),
                    ("Perundungan (Bullying)", "Perundungan (Bullying)"),
                    ("Kekerasan Seksual", "Kekerasan Seksual"),
                    ("Diskriminasi dan Intoleransi", "Diskriminasi dan Intoleransi"),
                    (
                        "Kebijakan yang Mengandung Kekerasan",
                        "Kebijakan yang Mengandung Kekerasan",
                    ),
                ],
                default="Kekerasan Seksual",
                max_length=120,
                verbose_name="Jenis Dugaan Kekerasan",
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="link_pelaporan",
            field=models.URLField(
                blank=True,
                help_text="Link Google Drive/OneDrive untuk kronologi lengkap",
                verbose_name="Link Kronologi Lengkap",
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="lokasi",
            field=models.CharField(
                default="", max_length=255, verbose_name="Tempat Kejadian"
            ),
        ),
    ]
