# Generated by Django 5.2.7 on 2025-12-06 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_customuser_fakultas_customuser_is_profile_complete_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="keterangan",
            field=models.CharField(
                blank=True, help_text="Keterangan bukti tambahan", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="evidence",
            name="uploaded_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Siapa yang upload (admin atau pelapor)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PelaporResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pesan", models.TextField(help_text="Pesan/balasan dari pelapor")),
                ("tanggal", models.DateTimeField(auto_now_add=True)),
                (
                    "laporan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pelapor_responses",
                        to="users.laporan",
                    ),
                ),
                (
                    "progress",
                    models.ForeignKey(
                        blank=True,
                        help_text="Progress yang dibalas (opsional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.progress",
                    ),
                ),
            ],
            options={
                "ordering": ["tanggal"],
            },
        ),
    ]
