# Generated by Django 5.2.7 on 2025-12-06 05:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0023_evidence_keterangan_evidence_uploaded_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="fakultas",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Fakultas Teknik Elektro", "Fakultas Teknik Elektro"),
                    ("Fakultas Rekayasa Industri", "Fakultas Rekayasa Industri"),
                    ("Fakultas Informatika", "Fakultas Informatika"),
                    ("Fakultas Ekonomi dan Bisnis", "Fakultas Ekonomi dan Bisnis"),
                    ("Fakultas Industri Kreatif", "Fakultas Industri Kreatif"),
                    ("Fakultas Ilmu Terapan", "Fakultas Ilmu Terapan"),
                ],
                max_length=100,
                null=True,
                verbose_name="Fakultas",
            ),
        ),
        migrations.CreateModel(
            name="RekamMedisKonseling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sesi_ke",
                    models.PositiveIntegerField(default=1, help_text="Sesi keberapa"),
                ),
                ("tanggal_sesi", models.DateTimeField(auto_now_add=True)),
                (
                    "diagnosis_awal",
                    models.CharField(
                        blank=True,
                        help_text="Diagnosis awal (jika ada)",
                        max_length=500,
                    ),
                ),
                (
                    "mood_klien",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="Skala mood 1-10 (1=sangat buruk, 10=sangat baik)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "risiko_bunuh_diri",
                    models.CharField(
                        choices=[
                            ("rendah", "Rendah"),
                            ("sedang", "Sedang"),
                            ("tinggi", "Tinggi"),
                            ("tidak_ada", "Tidak Ada"),
                        ],
                        default="tidak_ada",
                        help_text="Assessment risiko bunuh diri",
                        max_length=20,
                    ),
                ),
                (
                    "risiko_self_harm",
                    models.CharField(
                        choices=[
                            ("rendah", "Rendah"),
                            ("sedang", "Sedang"),
                            ("tinggi", "Tinggi"),
                            ("tidak_ada", "Tidak Ada"),
                        ],
                        default="tidak_ada",
                        help_text="Assessment risiko self-harm",
                        max_length=20,
                    ),
                ),
                (
                    "catatan_konselor",
                    models.TextField(
                        help_text="Catatan lengkap konselor tentang sesi (CONFIDENTIAL - tidak bisa dilihat klien)"
                    ),
                ),
                (
                    "intervensi_diberikan",
                    models.TextField(
                        blank=True,
                        help_text="Teknik/intervensi yang digunakan (CBT, mindfulness, dll)",
                    ),
                ),
                (
                    "progress_notes",
                    models.TextField(
                        blank=True, help_text="Catatan progress/perkembangan klien"
                    ),
                ),
                (
                    "rencana_tindak_lanjut",
                    models.TextField(
                        blank=True,
                        help_text="Rencana untuk sesi berikutnya atau rujukan",
                    ),
                ),
                (
                    "sesi_selanjutnya",
                    models.DateField(
                        blank=True,
                        help_text="Tanggal rencana sesi berikutnya",
                        null=True,
                    ),
                ),
                (
                    "file_lampiran",
                    models.FileField(
                        blank=True,
                        help_text="File pendukung (assessment form, dll)",
                        null=True,
                        upload_to="rekam_medis/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="Konselor yang membuat rekam medis",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rekam_medis_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "konseling",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rekam_medis",
                        to="users.booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rekam Medis Konseling",
                "verbose_name_plural": "Rekam Medis Konseling",
                "ordering": ["-tanggal_sesi"],
            },
        ),
    ]
