# Generated by Django 5.2.7 on 2025-12-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0024_alter_customuser_fakultas_rekammediskonseling"),
    ]

    operations = [
        migrations.AddField(
            model_name="laporan",
            name="ciri_ciri_pelaku",
            field=models.TextField(
                blank=True,
                help_text="Deskripsi fisik, pakaian, tanda khusus, dll",
                null=True,
                verbose_name="Ciri-ciri Pelaku (Deskripsi Fisik)",
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="jenis",
            field=models.CharField(
                choices=[
                    ("Kekerasan Fisik", "Kekerasan Fisik"),
                    ("Kekerasan Psikis", "Kekerasan Psikis"),
                    ("Kekerasan Fisik dan Psikis", "Kekerasan Fisik dan Psikis"),
                    ("Perundungan (Bullying)", "Perundungan (Bullying)"),
                    ("Kekerasan Seksual", "Kekerasan Seksual"),
                    ("Diskriminasi dan Intoleransi", "Diskriminasi dan Intoleransi"),
                    (
                        "Kebijakan yang Mengandung Kekerasan",
                        "Kebijakan yang Mengandung Kekerasan",
                    ),
                    ("Lainnya", "Lainnya"),
                ],
                default="Kekerasan Seksual",
                max_length=120,
                verbose_name="Jenis Dugaan Kekerasan",
            ),
        ),
        migrations.AlterField(
            model_name="laporan",
            name="jumlah_terlapor",
            field=models.CharField(
                blank=True,
                help_text="Jika lebih dari 1, pisahkan dengan koma",
                max_length=255,
                null=True,
                verbose_name="Jumlah Terlapor",
            ),
        ),
    ]
