# Generated by Django 5.2.7 on 2025-12-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0025_laporan_ciri_ciri_pelaku_alter_laporan_jenis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="ciri_ciri_pelaku",
            field=models.TextField(
                default=1,
                help_text="Deskripsi fisik, pakaian, tanda khusus, dll",
                verbose_name="Ciri-ciri Pelaku (Deskripsi Fisik)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="laporan",
            name="kronologi_singkat",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Ringkasan singkat kejadian",
                verbose_name="Kronologi Singkat",
            ),
        ),
    ]
