# Generated by ChatGPT on 2025-12-11
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_laporan_ciri_ciri_pelaku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_pribadi',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Pribadi'),
        ),
    ]
