# Generated by Django 5.2.7 on 2025-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_customuser_email_pribadi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="link_pelaporan",
            field=models.URLField(
                blank=True,
                help_text="Link Google Drive/OneDrive untuk kronologi lengkap",
                max_length=1000,
                verbose_name="Link Kronologi Lengkap",
            ),
        ),
    ]
