# Generated by Django 5.2.7 on 2025-12-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_alter_laporan_link_pelaporan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laporan",
            name="ai_kategori",
            field=models.CharField(
                blank=True,
                help_text="Kategori otomatis dari AI",
                max_length=100,
                null=True,
            ),
        ),
    ]
